#!/usr/bin/env bash
# shellcheck disable=SC2086
# configure domain zone and display information about subdomains

display_dig_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ];  # if parameter #2  zero length or equal to subdomain
    then
	display_dig_info "$1" "$subdomain"
    fi
done
