#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /usr/share/nginx/html/index.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
service nginx restart
