#!/usr/bin/env bash
# redirecting

 config_to_redirect=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

             rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        location / {
                try_files \$uri \$uri/ =404;
        }
        
        # if (\$request_filename ~ redirect_me){
          # rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        # }
}
"

 echo "$config_to_redirect" > /etc/nginx/sites-available/default
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
