#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World! inside

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

# config_to_redirect=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

            # rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
             sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'/etc/nginx/sites-available/default
        location / {
                try_files \$uri \$uri/ =404;
        }
        
        # if (\$request_filename ~ redirect_me){
          # rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        # }
}
"

# echo '$config_to_redirect' > /etc/nginx/sites-available/default
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
