#!/usr/bin/env bash
#use of while, if , elif and else statements
k=1
while [ $k -le 10 ]
do
	if [ $k -eq 4 ]
	then
		echo "bad luck"
	elif [ $k -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((k++))
done
