#!/usr/bin/env bash                                                            
# set up Nginx to run as nginx user
# nginx must be listening on all active IPs on port 8080                                               
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/d\
efault
sudo useradd nginx
chown nginx:nginx /etc/nginx/nginx.conf  
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
#service nginx reload
#service nginx restart
