#!/usr/bin/env bash
# Run nginx as nginx
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chown 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
