#!/usr/bin/env bash
# Creating a RSA key pair
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty
ssh-keygen -f school -b 4096 -N betty
